---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - include_vars: dimensiondata_vars.yml
    - name: Create MCP 1.0 network
      dimensiondata_network:
        region: "{{region}}"
        location: NA5
        name: ansible-test1
    - name: Create MCP 2.0 network
      dimensiondata_network:
        region: "{{region}}"
        location: NA9
        name: ansible-test2
