---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - include_vars: dimensiondata_vars.yml
    - name: Create MCP 2.0 firewall rule
      dimensiondata_firewall:
        region: "{{region}}"
        location: "{{location}}"
        network_domain: "{{network_domain_firewall}}"
        name: ansible_test1
        state: "{{state_enabled}}"
        action: ACCEPT_DECISIVELY
        ip_version: IPv4
        protocol: TCP
        source: ANY
        source_port: ANY
        destination: 168.128.28.100
        destination_port: 5555
        position: BEFORE
        relative_to_rule: SSH_Alt
